name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test basic imports
      run: |
        echo "Testing basic imports..."
        PYTHONPATH=. python -c "import src.models; print('✅ Models imported successfully')"
        PYTHONPATH=. python -c "import src.utils.parsing; print('✅ Parsing utils imported successfully')"
        PYTHONPATH=. python -c "import src.utils.scoring; print('✅ Scoring utils imported successfully')"
        echo "🎉 All imports working!"
        
    - name: Validate configuration
      run: |
        echo "Validating configuration..."
        PYTHONPATH=. python -c "
        import yaml
        with open('configs/sources.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print(f'✅ Found {len(config.get(\"retailers\", []))} retailers configured')
        print('✅ Configuration file is valid')
        "
        
    - name: Test CLI module
      run: |
        echo "Testing CLI module..."
        PYTHONPATH=. python -c "import src.cli; print('✅ CLI module imported successfully')"
        echo "🎉 Basic functionality test passed!"
      continue-on-error: true
