name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: playwright install --with-deps
      
    - name: Run basic validation
      run: |
        echo "Testing basic imports..."
        python -c "import src.models; print('Models imported successfully')"
        python -c "import src.utils.parsing; print('Parsing utils imported successfully')"
        python -c "import src.utils.scoring; print('Scoring utils imported successfully')"
      env:
        PYTHONPATH: ${{ github.workspace }}
        
    - name: Test CLI help
      run: |
        python -m src.cli --help
      env:
        PYTHONPATH: ${{ github.workspace }}
      continue-on-error: true
        
    - name: Validate configuration
      run: |
        python -c "
        import yaml
        with open('configs/sources.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print(f'Found {len(config.get(\"retailers\", []))} retailers configured')
        "
      env:
        PYTHONPATH: ${{ github.workspace }}
      continue-on-error: true
